AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-authorizer

  Lambda authorizer for Auth0
  
Globals:
  Function:
    Timeout: 3

Parameters:
  JwksUri:
    Type: String
  Audience:
    Type: String
  TokenIssuer:
    Type: String


Resources:
#  ServerlessAPI:
#    Type: AWS::Serverless::Api
#    Properties:
#      StageName: Dev
#      Auth:
#        DefaultAuthorizer: Auth0Authorizer
#        Authorizers:
#          Auth0Authorizer:
#            FunctionPayloadType: TOKEN
#            FunctionArn: !GetAtt Auth0AuthorizerFunction.Arn
#            Identity:
#              Header: Authorization
#              ValidationExpression: ^Bearer [-0-9a-zA-Z\._]*$
#              ReauthorizeEvery: 0

  Auth0AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-authorizer/
      Handler: auth.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          JWKS_URI: !Ref JwksUri
          AUDIENCE: !Ref Audience
          TOKEN_ISSUER: !Ref TokenIssuer

#  HelloWorldFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: hello-world/
#      Handler: app.lambdaHandler
#      Runtime: nodejs10.x
#      Events:
#        HelloWorld:
#          Type: Api
#          Properties:
#            Path: /hello
#            Method: get
#            RestApiId: !Ref ServerlessAPI
